---
name: Samba NAS
version: 10.0.2-nas3
slug: sambanas
description: Expose Home Assistant disc with SMB/CIFS
url: https://github.com/dianlight/hassio-addons/tree/master/sambanas
codenotary: lucio.tarantino@gmail.com
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: system
boot: auto
init: false
hassio_api: true
hassio_role: admin
host_network: true
map:
  - config:rw
  - ssl:rw
  - addons:rw
  - share:rw
  - backup:rw
  - media:rw
options:
  workgroup: WORKGROUP
  username: homeassistant
  allow_hosts:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    - 169.254.0.0/16
    - fe80::/10
    - fc00::/7
  automount: true
  moredisks: []
  available_disks_log: true
  medialibrary:
    enable: false
  veto_files:
    - "._*"
    - ".DS_Store"
    - Thumbs.db
    - icon?
    - ".Trashes"
  compatibility_mode: false
  wsdd2: false
  mqtt_use_legacy_entities: false
  autodiscovery: {}
  other_users: []
  acl: []
  interfaces: []
schema:
  workgroup: str
  username: str
  password: password
  automount: bool?
  moredisks:
    - str
  available_disks_log: bool?
  medialibrary:
    enable: bool?
    ssh_private_key: password?
  allow_hosts:
    - str
  veto_files:
    - str
  compatibility_mode: bool?
  wsdd2: bool?
  hdd_idle_seconds: int(0,)?
  enable_smart: bool?
  mqtt_use_legacy_entities: bool?
  mqtt_enable: bool?
  mqtt_host: str?
  mqtt_username: str?
  mqtt_password: password?
  mqtt_port: str?
  mqtt_topic: str?
  autodiscovery:
    disable_discovery: bool?
    disable_persistent: bool?
    disable_autoremove: bool?
  other_users:
    - username: str
      password: str
  acl:
    - share: str
      disabled: bool?
      users:
        - str?
      ro_users:
        - str?
      timemachine: bool?
  interfaces:
    - str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  meaning_of_life: int?

image: dianlight/{arch}-addon-sambanas
services:
  - mqtt:want
udev: true
#usb: true
host_dbus: true
kernel_modules: true
privileged:
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_RESOURCE
  - SYS_MODULE
full_access: true
devicetree: false
apparmor: true
host_ipc: true
#advanced: true
homeassistant: 2023.06.0
backup: hot
# Gemt Points!!!
auth_api: true

