[tool.poetry]
name = "sambanas-util"
version = "1.0.1"
description = "Utility for SambaNas Addon"
authors = ["dianlight <lucio.tarantino@gmail.com>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
pySMART = "^1.3.0"
psutil = "^7.0.0"
humanize = "^4.9.0"
diskinfo = "^3.1.1"
ha-mqtt-discoverable = "^0.19.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
